server:
  port: ${BACKEND_PORT}
  servlet:
    session:
      timeout: 30d # 30 days
      persistent: true # session data will be stored in the database
      cookie:
        max-age: 30d

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if- no-handler-found: true
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 110MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  data:
    redis:
      database: 0
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  #连接池最大连接数（使用负值表示没有限制）
  #spring.redis.jedis.pool.max-active=8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #spring.redis.jedis.pool.max-wait=-1
  # 连接池中的最大空闲连接
  #spring.redis.jedis.pool.max-idle=8
  # 连接池中的最小空闲连接
  #spring.redis.jedis.pool.min-idle=0
  # 连接超时时间（毫秒）
  #spring.redis.timeout=300

# S3配置
s3:
  bucket_name: ${S3_BUCKET_NAME}
  access_key: ${S3_ACCESS_KEY}
  secret_key: ${S3_SECRET_KEY}
  endpoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  domain: ${S3_DOMAIN}

# 其余配置
default_avatar: ${DEFAULT_AVATAR}