server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if- no-handler-found: true
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: search-service
  cloud: # 服务注册
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
